name: MobHunting
version: 1.3

main: au.com.mineauz.MobHunting.MobHunting

author: Schmoller

depend: [Vault]
softdepend: [Minigames]

commands:
  mobhunt:
    description: Allows you to configure mob hunt
    permission: mobhunting.cmd
    aliases: [mob,mh,hunt]
    usage: /<command> reload

permissions:
  mobhunting.enable:
    description: Allows mobhunting to be enabled for a player
    default: true
  mobhunting.cmd:
    description: Allows a player to use the mobhunt command
    default: true
  mobhunting.reload:
    description: Allows a player to reload the config
    default: op
    children:
      mobhunting.cmd: true
  mobhunting.listachievements:
    description: Allows a player to see all their achievements
    default: true
    children:
      mobhunting.cmd: true    
  mobhunting.listachievements.other:
    description: Allows a player to see another players achievements
    default: op
    children:
      mobhunting.listachievements: true
  mobhunting.checkgrinding:
    description: Allows a player to check whether the region they are in is a known grinding area 
    default: op
    children:
      mobhunting.cmd: true